feat: improve test and describe rendered title #70
amiceli/vitest-cucumber pull request #72
Opened 2024-05-02 21:40 UTC by amiceli

2024-05-02 23:21 UTC, charlieforward9 requested changes

2024-05-02 23:21 UTC, charlieforward9 commented on src/vitest/describe/scenarioOutline.ts
> +                key : `${stepType}: ${stepDetails}`,
Following the standard Cucumber syntax, it makes sense to leave the colon out of the step key.

> ["When Cucumber tries to execute a step, it looks for a matching step definition to execute."](https://cucumber.io/docs/gherkin/reference/#:~:text=when%20cucumber%20tries%20to%20execute%20a%20step%2C%20it%20looks%20for%20a%20matching%20step%20definition%20to%20execute.)

```suggestion
                key : `${stepType} ${stepDetails}`,
```

2024-05-03 06:18 UTC, amiceli commented on src/vitest/describe/scenarioOutline.ts
> +                key : `${stepType}: ${stepDetails}`,
Yes, I wanted to add colon to Scenario etc.
I will remove it for steps ;).

2024-05-03 20:27 UTC, amiceli commented
I try with vitest vscode extension, it's ok.
I'm going to publish a new version.

2024-05-03 20:29 UTC, charlieforward9 commented
Before you finish, is there a simple way of preserving the step order in the test navigator? My steps are rendering out of order.

2024-05-03 20:57 UTC, amiceli commented
I publish `3.2.5`, I saw your message too late ;).

For steps order, I've same thing on vscode, for example `Then` before `When`.
I thing it's an alphabetically order in vitest extension.

2024-05-03 20:58 UTC, merged